### ISSUE TITLE
How did you publish the package?

### ISSUE THREAD

**Issue by rikusen0335** [hashlucifer/react-coach-mark#4]
I had to publish some changes to npm registry, would you add me as an publisher or could you publish it?

**Comment by rikusen0335** [comment]
If you publish new package, please cocnsider to merge #3 before

**Comment by hashlucifer** [comment]
Whats your npm email? i'll add you as well with npm packge maintainer

**Comment by rikusen0335** [comment]
Thanks. mine is rikusen0335@gmail.com

**Comment by rikusen0335** [comment]
Btw do you admit MIT License? I am actually worried about you don't like to set license to MIT.

**Comment by rikusen0335** [comment]
Okay I got it
